<a href="https://colab.research.google.com/github/samvillasmith/RNN_Project/blob/main/embedding.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [14]:
from tensorflow.keras.preprocessing.text import one_hot

In [15]:
sentences = [  'the glass of milk',
     'the glass of juice',
     'the cup of tea',
    'I am a good boy',
     'I am a good developer',
     'understand the meaning of words',
     'your videos are good',]

In [16]:
# Define the vocabulary size
vocab_size = 10000

In [17]:
# One Hot Representation for every word
one_hot_rep = [one_hot(words, vocab_size) for words in sentences]
one_hot_rep


[[6158, 3414, 2158, 2671],
 [6158, 3414, 2158, 3412],
 [6158, 6450, 2158, 8960],
 [485, 5253, 7553, 790, 7565],
 [485, 5253, 7553, 790, 4167],
 [9258, 6158, 1390, 2158, 9589],
 [5866, 3233, 8830, 790]]

In [18]:
# Word embedding representation

from tensorflow.keras.layers import Embedding
from tensorflow.keras.utils import pad_sequences
from tensorflow.keras.models import Sequential
import numpy as np

In [19]:
sent_length = 8
embedded_docs = pad_sequences(one_hot_rep, padding='pre', maxlen=sent_length)
print(embedded_docs)

[[   0    0    0    0 6158 3414 2158 2671]
 [   0    0    0    0 6158 3414 2158 3412]
 [   0    0    0    0 6158 6450 2158 8960]
 [   0    0    0  485 5253 7553  790 7565]
 [   0    0    0  485 5253 7553  790 4167]
 [   0    0    0 9258 6158 1390 2158 9589]
 [   0    0    0    0 5866 3233 8830  790]]


In [20]:
# feature representation
dim = 10

In [21]:
model = Sequential()
model.add(Embedding(vocab_size, dim, input_length=sent_length))
model.compile('adam', 'mse')

/usr/local/lib/python3.12/dist-packages/keras/src/layers/core/embedding.py:97: UserWarning: Argument `input_length` is deprecated. Just remove it.
  warnings.warn(


In [22]:
model.summary()

Model: "sequential_1"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding_1 (Embedding)         │ ?                      │   0 (unbuilt) │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 0 (0.00 B)

 Trainable params: 0 (0.00 B)

 Non-trainable params: 0 (0.00 B)

In [23]:
model.predict(embedded_docs)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 246ms/step


array([[[ 0.01824162, -0.03005115, -0.01261135,  0.00406485,
          0.04210094, -0.01304501,  0.00737318,  0.04459785,
          0.04982128, -0.01108671],
        [ 0.01824162, -0.03005115, -0.01261135,  0.00406485,
          0.04210094, -0.01304501,  0.00737318,  0.04459785,
          0.04982128, -0.01108671],
        [ 0.01824162, -0.03005115, -0.01261135,  0.00406485,
          0.04210094, -0.01304501,  0.00737318,  0.04459785,
          0.04982128, -0.01108671],
        [ 0.01824162, -0.03005115, -0.01261135,  0.00406485,
          0.04210094, -0.01304501,  0.00737318,  0.04459785,
          0.04982128, -0.01108671],
        [-0.03151714, -0.00247134, -0.02443547,  0.04410597,
          0.04107073,  0.03101028, -0.04752836,  0.00633346,
          0.02399294, -0.03956018],
        [-0.04554992,  0.0072534 , -0.04641278, -0.0453362 ,
         -0.01581837,  0.00273087,  0.03743077,  0.02763147,
         -0.01446409, -0.03879856],
        [-0.04725891,  0.0266526 , -0.04158759, -0.0

In [24]:
embedded_docs[0]

array([   0,    0,    0,    0, 6158, 3414, 2158, 2671], dtype=int32)

In [26]:
model.predict(np.expand_dims(embedded_docs[0], 0))

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 107ms/step


array([[[ 0.01824162, -0.03005115, -0.01261135,  0.00406485,
          0.04210094, -0.01304501,  0.00737318,  0.04459785,
          0.04982128, -0.01108671],
        [ 0.01824162, -0.03005115, -0.01261135,  0.00406485,
          0.04210094, -0.01304501,  0.00737318,  0.04459785,
          0.04982128, -0.01108671],
        [ 0.01824162, -0.03005115, -0.01261135,  0.00406485,
          0.04210094, -0.01304501,  0.00737318,  0.04459785,
          0.04982128, -0.01108671],
        [ 0.01824162, -0.03005115, -0.01261135,  0.00406485,
          0.04210094, -0.01304501,  0.00737318,  0.04459785,
          0.04982128, -0.01108671],
        [-0.03151714, -0.00247134, -0.02443547,  0.04410597,
          0.04107073,  0.03101028, -0.04752836,  0.00633346,
          0.02399294, -0.03956018],
        [-0.04554992,  0.0072534 , -0.04641278, -0.0453362 ,
         -0.01581837,  0.00273087,  0.03743077,  0.02763147,
         -0.01446409, -0.03879856],
        [-0.04725891,  0.0266526 , -0.04158759, -0.0